name = "avanza_commission"
version = "0.1"
description = "AVANZA Trade Performance Analysis"
author = "Emre Süren"
author_email = "siberkartal@gmail.com"

packages = ["pandas"]
[files]
"../commission/commission.py" = "commission.py"

